spring.application.name=user-service

#spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
#spring.datasource.username=joreid
#spring.datasource.password=joreid
#spring.jpa.database=POSTGRESQL
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mongodb.uri=mongodb://localhost:27017/userdb
spring.mongodb.database=userdb
server.port=8082
