spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=joreid
spring.datasource.password=joreid
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8083
